package chat.fray.event;

public enum EventType {
    HELLO,
    MESSAGE_CREATE,
    MESSAGE_UPDATE,
    MESSAGE_DELETE,
    CHANNEL_CREATE,
    CHANNEL_UPDATE,
    CHANNEL_DELETE,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,
    TYPING_START,
    TYPING_STOP,
    PRESENCE_UPDATE,
    MEMBER_JOIN,
    MEMBER_LEAVE,
    MEMBER_UPDATE,
    READ_STATE_UPDATE
}
